version: '3.4'

services: 
  jamplace-angular:
    image: rpetlak/jamplace-angularappdev:0.1
    container_name: angular_www
    ports:
     - "4200:4200"
     - "41154:49153"
    volumes:
     - ./JamPlace.AngularApp:/app
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: sa
      POSTGRES_USER: postgres
    ports:
     - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4
    hostname: "pgadmin"
    depends_on:
      - "db"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@db.pl"
      PGADMIN_DEFAULT_PASSWORD: "db123"
    volumes:
      - ./pgadmincfg/servers.json:/pgadmin4/servers.json
    ports:
      - "82:80"
      
  

